name: shopping_list_app
description: "A Shopping List aplication"
publish_to: 'Vortex'
version: 6.50.65

environment:
  sdk: '>=3.3.0-272.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lucide_icons_flutter: ^1.0.5
  flutter_riverpod: ^2.4.9
  uuid: ^4.3.3
  hooks_riverpod: ^2.4.9
  flutter_hooks: ^0.20.4
  text_scroll: ^0.2.0
  package_info_plus: ^5.0.1
  hive: ^2.2.3
  shared_preferences: ^2.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png"

flutter:
  
  uses-material-design: true
  fonts:
    - family: 'ShoppingFont'
      fonts:
        - asset: 'fonts/Montserrat-Regular.ttf'
        - asset: 'fonts/Montserrat-Medium.ttf'
          weight: 700
  assets:
    - 'assets/icon.png'
