name: shopping_list_app
description: "A Shopping List aplication"
publish_to: 'Vortex'
version: 1.12.0

environment:
  sdk: '>=3.3.0-272.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lucide_icons: ^0.257.0
  flutter_riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: 'ShoppingFont'
      fonts:
        - asset: 'fonts/Montserrat-Regular.ttf'
        - asset: 'fonts/Montserrat-Medium.ttf'
          weight: 700
          
